server:
  port: 8002
  address: 0.0.0.0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.0.102:8001/eureka
  instance:
    appname: GATEWAY-SERVICE
    prefer-ip-address: true
spring:
  application:
    name: GATEWAY-SERVICE
