spring:
  cloud:
    gateway:
      routes:
        - id: notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification
          filters:
            - name: CircuitBreaker
              args:
                name: notificationCircuitBreaker
                fallbackUri: forward:/notification/failure