spring:
  cloud:
    gateway:
      routes:
        - id: lms
          uri: lb://LMS-SERVICE
          predicates:
            - Path=/lms
          filters:
            - name: CircuitBreaker
              args:
                name: lmsCircuitBreaker
                fallbackUri: forward:/lms/failure