spring:
  cloud:
    gateway:
      routes:
        - id: lms
          uri: lb://LEARNING-MANAGEMENT-SYSTEM
          predicates:
            - Path=/lms/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: lmsCircuitBreaker
                fallbackUri: forward:/lms/failure